import Head from "next/head";
import Filter from "@/components/Filter";
import { Button, Col, Layout, List, Row, Table } from "antd";
import Map from "@/components/Map";
import warehousesSlice from "@/store/warehouses.slice";
import { observer } from "mobx-react-lite";
import "leaflet/dist/leaflet.css";
import LastPost from "@/components/Post/LastPost";
import { useLayoutEffect, useState } from "react";
import WarehousesTable from "@/components/Tables/WarehousesTable";
import LoadingSpinner from "@/components/LoadingSpinner";
import AdvertisingBanner from "@/components/AdvertisingBanner";

export default observer(function Home() {
  const [isFetched, setIsFetched] = useState<boolean>(false);

  async function getData() {
    setTimeout(() => {
      warehousesSlice.setFilteredWarehouses(
        warehousesSlice.region,
        warehousesSlice.locality,
        "Каа-Хемский уголь"
      );
      setIsFetched(true);
    }, 1000);
    // await warehousesSlice.getAllWarehouses();
  }
  useLayoutEffect(() => {
    if (isFetched === false) {
      getData();
    }
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {isFetched ? (
          <>
            <Row gutter={[24, 0]} className="pt-10">
              <Col span={15}>
                <Map />
              </Col>
              <Col span={9} order={2}>
                <Filter />
              </Col>
            </Row>

            {warehousesSlice.filteredWarehouses && (
              <WarehousesTable
                warehouses={warehousesSlice.filteredWarehouses}
              />
            )}

            <AdvertisingBanner/>
          </>
        ) : (
          <LoadingSpinner/>
        )}
      </div>
    </>
  );
});

export const ListItemDescription = ({ address, contacts }: any) => {
  return (
    <div
      style={{
        width: "100%",
        display: "flex",
        flexDirection: "row",
        gap: "30px",
        justifyContent: "space-between",
      }}
    >
      <Row
        style={{ width: "100%" }}
        wrap={true}
        align="middle"
        justify="space-between"
      >
        <Col span={8}>
          {address.region.type + " "}
          {address.region.name + ", "}
          {address.locality.type + " "}
          {address.locality.name + ", "}
          {address.street.type + " "}
          {address.street.name + ", "}
          {"дом " + address.street.number}
        </Col>
        <Col span={6}>
          {contacts.phones[0].phone}
          {contacts.emails[0].email}
        </Col>
        <Col span={2}>
          <Button type="primary">Перейти</Button>
        </Col>
      </Row>
    </div>
  );
};
