import Head from "next/head";
import Filter from "@/components/Filter";
import { Button, Col, Layout, List, Row } from "antd";
import Map from "@/components/Map";
import warehousesSlice from "@/store/warehouses.slice";
import { observer } from "mobx-react-lite";
import "leaflet/dist/leaflet.css";

export default observer(function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Row gutter={[24, 0]} className="pt-10">
          <Col span={15}>
            <Map />
          </Col>
          <Col span={9} order={2}>
            <Filter />
          </Col>
        </Row>

        <List
          itemLayout="horizontal"
          dataSource={warehousesSlice.filteredWarehouses}
          renderItem={(item, index) => (
            <List.Item key={item.id}>
              <List.Item.Meta
                title={item.title}
                description={
                  <ListItemDescription
                    address={item.address}
                    contacts={item.contacts}
                  />
                }
              />
            </List.Item>
          )}
        />

        <Row>
          <Col span={16} className="info__calculate">
            <div className="header__name__calculate">
              <h1 className="heading__calc">
                Воспользуйтесь онлайн калькулятором, чтобы узнать стоимость угля
                в вашем районе
              </h1>
              <p className="paraghrpaph__calculate">
                Калькулятор поможет рассчитать стоимость угля с учетом доставки
              </p>
            </div>
            <Button className="button">Рассчитать</Button>
          </Col>
          <Col span={7} className="coal">
            <div
              className="goal__images"
            >
              <img className="photo__rectangle_9"
                src="/Rectangle_9.png"
                alt=""
              />
              <div style={{ position: "absolute", bottom: 0 }}>
                <h1 className="heading__rectangle">
                  В Туве бесплатным углем обеспечат более 320 семей
                  </h1>
               <p className="paragrhaph__rectangle">
               5 марта 2023, 17:17
               </p>
              </div>
            </div>
          </Col>
        </Row>
        <Row style={{ marginTop: "20px" }}>
          <Col span={6}>
            <img className="Rectangle_10"
              src="/Rectangle_10.png"
              alt=""

            />
          </Col>
          <Col span={6}>
            <img className="Rectangle_12"
              src="/Rectangle_12.png"
              alt=""
            />
          </Col>
          <Col span={12}>
            <img className="Rectangle_11"
              src="/Rectangle_11.png"
              alt=""
            />
          </Col>
        </Row>
      </div>
    </>
  );
});

export const ListItemDescription = ({ address, contacts }: any) => {
  return (
    <div
      style={{
        width: "100%",
        display: "flex",
        flexDirection: "row",
        gap: "30px",
        justifyContent: "space-between",
      }}
    >
      <Row
        style={{ width: "100%" }}
        wrap={true}
        align="middle"
        justify="space-between"
      >
        <Col span={8}>
          {address.region.type + " "}
          {address.region.name + ", "}
          {address.locality.type + " "}
          {address.locality.name + ", "}
          {address.street.type + " "}
          {address.street.name + ", "}
          {"дом " + address.street.number}
        </Col>
        <Col span={6}>
          {contacts.phones[0].phone}
          {contacts.emails[0].email}
        </Col>
        <Col span={2}>
          <Button type="primary">Перейти</Button>
        </Col>
      </Row>
    </div>
  );
};
